name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.19"

      # Determine if this is a pre-release based on tag name
      - name: Check pre-release status
        id: prerelease
        run: |
          if [[ ${{ github.ref_name }} == *-alpha* || ${{ github.ref_name }} == *-beta* || ${{ github.ref_name }} == *-rc* ]]; then
            echo "IS_PRERELEASE=true" >> $GITHUB_OUTPUT
          else
            echo "IS_PRERELEASE=false" >> $GITHUB_OUTPUT
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Pass the pre-release flag to GoReleaser
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
          GORELEASER_PRERELEASE: ${{ steps.prerelease.outputs.IS_PRERELEASE }}
